module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CART_COLLECTION:'cart',
    CATEGORY_COLLECTION:'category',
    ORDER_COLLECTION:'order',
    ADDRESS_COLLECTION:'address',
    COUPON_COLLECTION:'coupon',
    OFFER_COLLECTION:'offer',
    WALLET_COLLECTION:'wallet',
    COUPON_HISTORY:'history',
    BANNER_COLLECTION:'banner'
}
